[package]
name = "bevy_hijinks"
version = "0.1.0"
authors = ["Lee Martin <lee.martin@pliminus.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"